# Generated by Django 2.1.1 on 2018-11-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passWord',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userStats',
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False, verbose_name='用户状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=456465, max_length=20, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
