# Generated by Django 2.1.1 on 2018-11-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181103_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=120, verbose_name='密码'),
        ),
    ]
