# Generated by Django 2.1.1 on 2018-11-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181103_0613'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='Users_userID_80d74e_idx',
        ),
    ]
